version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: baonguyen
      POSTGRES_DB: app-with-multiple-entity-types
      PG_DATA: /postgres/data
    restart: unless-stopped
    volumes:
      - postgres_data:/postgres/data

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: baonguyen
      MONGO_INITDB_ROOT_PASSWORD: 123

    volumes:
      - mongo_data:/mongo/data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: baonguyen
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb://baonguyen:123@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  postgres_data:
  mongo_data: